Table Customer {
  Customer_ID integer [primary key]
  Name varchar
  Email varchar
  Phone varchar
  created_at timestamp
}
Table Booking {
  Booking_ID integer [primary key]
  Customer_ID integer [not null]
  Show_ID integer
  Total_Amount decimal
  Booking_Type varchar [note: 'Single or Group']
  Status varchar [note: 'Confirmed, Pending, Cancelled']
  created_at timestamp
}
Table OnlineBooking {
  OnlineBooking_ID integer [primary key]
  Ticket_ID integer [not null]
  Transaction_ID varchar
  BookingPlatform varchar [note: 'Website, Mobile App']
  Status varchar [note: 'Pending, Confirmed, Cancelled']
}


